spring:
  profiles:
    active: dev # 激发开发环境配置

---

server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
  type-aliases-package: com.mrtao.springcloud.entities # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml  # mapper映射文件

spring:
  profiles: dev
  application:
    name: microservice-product-config # 服务与服务之间互相调用一般根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 10



eureka:
  client:
    register-with-eureka: true  # 服务注册开关
    fetchRegistry: true # 服务发现开关
    ServiceUrl:      #注册到哪个服务中心
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port} #指定实例ID
    prefer-ip-address: true #访问路径显示IP地址

---

server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
  type-aliases-package: com.mrtao.springcloud.entities # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml  # mapper映射文件

spring:
  profiles: prod
  application:
    name: microservice-product-config # 服务与服务之间互相调用一般根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 10



eureka:
  client:
    register-with-eureka: true  # 服务注册开关
    fetchRegistry: true # 服务发现开关
    ServiceUrl:      #注册到哪个服务中心
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port} #指定实例ID
    prefer-ip-address: true #访问路径显示IP地址
